# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fabnews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fabnews
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'

  target 'FabnewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FabnewsUITests' do
    # Pods for testing
  end

end
